### ISSUE TITLE
small error for method name `error_test`

### ISSUE THREAD

**Issue by larrycai** [blueswen/fastapi-jaeger#1]
````python
@app.get("/error_test")
async def random_sleep(response: Response):
````

it shall be `error_test`

`f"http://localhost:8000/"` here `f` is not needed.

**Comment by blueswen** [comment]
Nice catch! Thanks for reminding.  Already fixed in https://github.com/blueswen/fastapi-jaeger/commit/56bf7016a60c523c47274dd49ee88c70da5d4b48.
