### ISSUE TITLE
How to combine SPM with grafana?

### ISSUE THREAD

**Issue by npuichigo** [blueswen/fastapi-jaeger#6]
Fantastic repo. I want to know if there's a way to show SPM in grafana?

**Comment by blueswen** [comment]
Hi @npuichigo,

I have another project https://github.com/blueswen/opentelemetry-apm only using Span Metrics Connector to monitor System/Application performance like Jaeger SPM.

**Comment by npuichigo** [comment]
Which one do you prefer? I only want to find a easy way to tracing my service, and it's fine to use jaeger or not.

**Comment by blueswen** [comment]
Using Jaeger SPM is the easiest way if you don't have or need other metrics from your applications.

**Comment by npuichigo** [comment]
I found your another repo https://github.com/blueswen/fastapi-observability/tree/main and it's great for me. By the way,  how can I include opentelemetry trace id in response header for user to help debugging?

**Comment by blueswen** [comment]
We can discuss the following question at https://github.com/blueswen/fastapi-observability/issues/12.
